### PR TITLE
Add BaseComponent with shouldComponentUpdate

### LINKED ISSUE #71: Add base shouldComponentUpdate globally (or at least many places locally)?
Wouldn't this be a really good idea? I can already see now there are heaps of unnecessary renders of components going on, and I think this might be part of the problem with #70.

I would imagine an implementation that looked something like a BaseComponent that all React Components extend.

### PR DESCRIPTION
**Pull request by emilgoldsmith**
Added a BaseComponent and made all components extend it, questions I can identify that are up for discussion are:

 - Where should BaseComponent be in the folder structure? Right now I put it in App as I kind of didn't feel it fits in either components or container as it's abstract in the sense that it doesn't have a render function. We could keep it in app or we could maybe make a new folder such as lib?

 - What do you think of the current shouldComponentUpdate? We could of course do a comprehensive equals as it also looks like we don't have any big objects in props or state currently so it probably wouldn't hurt performance too much, though it's dangerous starting to do all out equals, if we did that we could use a library such as lodash.

Looking forward to hear thoughts.

Also: This resolves #71 and fixes some of #70 as it stops the bug where opening the hide option will make hidden html elements re-appear (but doesn't solve all of #70 's problems).

### CODE REVIEW

**Comment by martynchamberlin** [comment]
@emilgoldsmith You'll notice that this PR is failing CI since `yarn run lint` isn't passing.

**Comment by emilgoldsmith** [comment]
Yep I'll fix linting.

And yeah I guess it would be nice with a fundamental shouldComponentUpdate, with it still being obvious that you can change it if you want. I'm not familiar with what VueJS's fundamental implementation, but it would definitely be awesome not to have to think about it, as I guess in by far most cases you won't need a custom shouldComponentUpdate.

But you're all good with my decision for the shouldComponentUpdate / Placing the BaseComponent.js in the app/ folder? 
As in choice of just doing a shallow comparison instead of a deep one, and the placement of BaseComponent.js

When we make the choice of a shallow comparison, this would currently mean that you have to remember to always change keys of an object in state or props, mutating just one of the `keys of the keys` would not make anything change. So future developers just have to be aware of that of course.

This is the shouldComponentUpdate I use on the newspaper project I run though, and I think it works well.

**Comment by martynchamberlin** [comment]
Yeah this works. If it ever becomes an issue then we can revisit it later!

**Comment by emilgoldsmith** [comment]
Okay, just merged master in here to have it updated, and now I'll merge the PR back into master.

**Pull request merged**
