### PR TITLE
Remove the page reload when pressing reset

### LINKED ISSUE #63: Avoid page refresh whenever a style reset occurs
Right now, whenever a user tries to reset a UI customization, the Chess.com page refreshes. We have to do this refresh with our current setup because the plugin injects the stylesheet into the browser and while we could override this, we need to be able to actually remove the inject stylesheet (or at least modify it, to remove the pertinent elements) when the user clicks a reset button. 

This modification / removal of the injected stylesheet looks to be possible. http://stackoverflow.com/questions/18533820/how-do-i-remove-an-injected-css-file 

What I propose is instead of constantly manipulating this injected stylesheet every time the user resets something, we instead:

- Inject the stylesheet initially on page load, so as to avoid FOUC.
- Once this occurs, add the styling as inline
- Remove the injected stylesheet 
- Then in the future, when the user wants to reset something, simply remove the inline styling

This will avoid page refresh whenever a style reset occurs and it will make for a vastly superior user experience.

### PR DESCRIPTION
**Pull request by emilgoldsmith**
This PR will end up removing the need for a page reload when pressing reset by implementing the approach outlined in #63. (resolves #63)

Currently I have just added the initial commit to check in with @martynchamberlin and anyone else that my starting approach looks okay.

### CODE REVIEW

**Comment by emilgoldsmith** [comment]
Oh yeah, sorry, I think you misunderstood me!

I didn't get that far yet. I simply successfully added a class to all the initially injected styles, and successfully added that class to the body element before initial render by using mutation observers. I haven't added the actual showing / not showing functionality yet. I just wanted to check in with you before I kept working that this was the kind of approach you were thinking of?

So there's nothing to physically test just as of yet, just code to look at.

**Comment by martynchamberlin** [comment]
Gotcha. Carry on!

**Comment by emilgoldsmith** [comment]
Cool. 

So this was the kind of approach you were thinking of using in #80 yeah?

**Comment by martynchamberlin** [comment]
Yeah I hadn't thought of your solution but it's brilliant and solves the problem in an elegant way.

**Comment by emilgoldsmith** [comment]
Awesome. It was simply my interpretation of what you suggested in #63  haha!

**Comment by emilgoldsmith** [comment]
Still very much a work in progress, but now the reset all button correctly removes all applied inline styles (it's currently assuming that Chess.com don't apply any themselves as it simply clears all inline styles, I'm assuming that's a correct assumption?)

Todo:
- After load complete actually remove the temp stylesheet and apply all the inline styles, I already started writing this code
- Integrate the rest of the reset buttons for the colorpicker into my new design
- Hunt down any other page reloads every being requested like for example the font one.

**Comment by emilgoldsmith** [comment]
Okay, I seem to have the basics working now! Any thoughts @martynchamberlin ?

I'm still lacking point 2 and three from above. But normal style changing and the reset all button should be working as intended now!

**Comment by martynchamberlin** [comment]
Looking great. I'm noticing that we're reloading the whole page on an individual reset button click. Maybe we can remove that too in this PR?

**Comment by emilgoldsmith** [comment]
Yep that's still on the to do as mentioned above about point two and three:

> - Integrate the rest of the reset buttons for the colorpicker into my new design
> - Hunt down any other page reloads every being requested like for example the font one.

**Comment by emilgoldsmith** [comment]
The two above points have now been implemented!

Basically there now, I might do a few more checks and have a few edge cases I'd like to test at some point before we merge it though.

But as always, feel free to play around with it / check out the code and give any comments you might have.

**Comment by emilgoldsmith** [comment]
I think I'm happy with this PR now, I opened some issues #92 and #93 which are things I thought of while doing this, but also think they aren't necessarily directly related to this PR so made them issues instead. I believe the PR now has achieved what it set out to achieve ;).

@martynchamberlin if you could look through it a final time and review if all is good?

**Comment by emilgoldsmith** [comment]
Awesome I'll get around to fixing conflicts with master and get it merged in.

**Comment by emilgoldsmith** [comment]
That was quite a hairy merge but I'm quite certain I got it all, tested it and looked through the new diff here on the PR after, so I'll merge it in.

**Pull request merged**
