### PR TITLE
force a vertical scrollbar to avoid a jumpy experience

### LINKED ISSUE #72: Hide scrollbar when opening an option?
Is it only me that feels like this is a small nuisance in the design? The extension will jump when you open an option because the scrollbar pops up and moves everything to the left.

### PR DESCRIPTION
**Pull request by emilgoldsmith**
Resolves #72.

@martynchamberlin any thoughts? Does it look okay on Windows etc. ?

### CODE REVIEW

**Comment by emilgoldsmith** [comment]
Hi Martyn,

Sucks that front-end is so complicated and full of edge cases! I completely agree that we could nearly disregard behaviour in Ubuntu as I'm sure by far majority of users are on Mac or Windows, but I was wondering whether you tried removing those two changes of the 300 to 320 and running it, but still keeping `overflow-y: scroll;` ? Because on my Ubuntu then I get this:
screenshot from 2017-03-17 16-55-23
screenshot from 2017-03-17 16-58-17

Which is obviously horrible. 

I guess this means in order to make this PR a success we would either need to change CSS of other elements to make everything work in harmony, or drop this idea I guess?

Also just to make completely sure that I understand, what you mean is that with original CSS all the buttons are aligned to the right with the two top ones yeah? And that's what's breaking on Mac at the moment?

**Comment by martynchamberlin** [comment]
So here's what I'm thinking: 

1. On Mac and on any other environment in which the scrollbar presence or absence has no bearing (pretty sure this is unique to macOS) change nothing from what it currently is in `master`. Nothing's breaking on Mac with `master`.
2. On all other platforms, all of the changes you've made in this PR are correct. 

That solves all the problems. Yes?

**Comment by emilgoldsmith** [comment]
Okay so you've tested it on Windows and it works well there? And on MacOS it doesn't do the jumps with the old code that I was trying to avoid?

I can try and send up a commit here for you to test as I don't have a Mac available and I know it's illegal to run Mac VM's on non Mac computers (duh... Apple...).

I'll write here again when it's ready.

**Comment by martynchamberlin** [comment]
Yes and yes!

**Comment by emilgoldsmith** [comment]
Okay, I think all should be good now.

My current commit here means we'd be rendering the popup asynchronously, but for one I'm sure getPlatformInfo is a very quick asynchronous function, and on the other hand I'd also rather have a slight delay (even though again, it's probably in the ms range) than a semi FOUC.

If @martynchamberlin could check it out on OSX that'd be great.

**Comment by martynchamberlin** [comment]
Looks good on macOS!

**Comment by emilgoldsmith** [comment]
Awesome, so do you want to approve the changes, I'll fix the conflicts with the new code, and I'll merge it in :)

**Pull request merged**
